version: "2.0"
services:  
    PlayList.IdentityServer:
        image: img_identity-server
        container_name: c_identity-server
        ports: ["7001:5001","7000:5000"] 
        command: dotnet tool install --global dotnet-ef

        build: 
            context: .
            dockerfile: IdentityDockerfile 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:7001;http://+:7000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - $PATH:/root/.dotnet/tools
        volumes:
            - ~/.aspnet/https:/https:ro
        depends_on: 
            - db 
    PlayList.Managerment.WebApi:
        image: img_managerment
        container_name: c_managerment
        ports: ["8001:5001","8000:5000"]
        build: 
            context: .
            dockerfile: ManagermentDockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:8001;http://+:8000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.aspnet/https:/https:ro
        depends_on: 
            - db
    PlayList.Customer.WebApi:
        image: img_customer
        container_name: c_customer
        ports: ["9001:5001","9000:5000"]
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:9001;http://+:9000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.aspnet/https:/https:ro
        build: 
            context: .
            dockerfile: CustomerDockerfile
        depends_on: 
            - db

    db:
        image: mysql
        container_name: c_play-list-mysql
        ports: ["3367:3306"]
        environment: 
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: PlayListDataBase
        